#官方
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://admin:123456@localhost:8000/eureka/

#裴少伯
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://admin:123456@10.9.21.178:8000/eureka/

#徐诗豪
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://admin:123456@10.9.21.230:8000/eureka/

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@10.9.21.225:8000/eureka/

#zookeeper注册中心配置
regCenter:
  #zookeeper注册中心IP与端口列表
#  serverList: 192.168.157.152:2181
  serverList: 114.242.146.109:8603,114.242.146.109:8602,114.242.146.109:8601
  #Zookeeper的命名空间
  namespace: elastic-job-lite-smsplatform-five

# rabbitMQ配置信息
spring:
  rabbitmq:
    host: rabbitmq.qfjava.cn
    port: 8800
    username: Five
    password: 123
    virtual-host: /Five
