server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8000/eureka/

#rabbitMQ配置信息
spring:
  rabbitmq:
    host: rabbitmq.qfjava.cn
    port: 8800
    username: Five
    password: 123
    virtual-host: /Five