server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@10.9.21.230:8000/eureka/

#rabbitMQ配置信息
spring:
  rabbitmq:
    host: 10.9.21.198
    port: 5672
    username: Five
    password: 123
    virtual-host: /Five