server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8000/eureka/

#rabbitMQ配置信息
spring:
  rabbitmq:
    host: 10.9.21.198
    port: 15672
    username: guest
    password: guest
